### ISSUE TITLE
MMS-Monthly Report Tab

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#117]
Quick Membership Count Report
I enter todays date 8/20/2019 and click on Export
this is the report I get:
[MembershipQuickMembershipCountReport-2900 (7).xlsx](https://github.com/stellaballa/AERA/files/3521733/MembershipQuickMembershipCountReport-2900.7.xlsx)
This is incorrect. I added 1 new member yesterday and the number should be 2018

The Prosis report also seems off. I do the same and get the incorrect count of 1380
and it should be 1381.

Not sure when this happened but it was correct last week.

If you go the MMS Tab, Click on Current, Click on Membership Only box, and the count is 2018 which is correct
Do the same and click on Prosis Pro only and the count is 1381 which is correct.

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look?

**Comment by kbt1** [comment]
Also when I run this report under Monthly Report Tab
**Active Member Locator - Website**
Starting Active Date 8/20/2019 
and Forward and click export, only 2003 companies come up on my list which is off by 17.

**Comment by SagarPC** [comment]
Please see below for the explanation on this report issue.

******************** **Quick Membership Count Report** ******************** 

**Membership:** I exported report for the 20th Aug 2019 and it's showing 2019 and it's correct. If you fail to add expiry date for the member then that member will not be considered under this report. 
[MembershipQuickMembershipCountReport-8802.xlsx](https://github.com/stellaballa/AERA/files/3524968/MembershipQuickMembershipCountReport-8802.xlsx)

**Prosis Pro:** I exported report and notice like a newly added member# 44577 not consider because of Trial account. We are only exporting non-trial member for the Prosis Pro as per the requirement.

![image](https://user-images.githubusercontent.com/31076567/63426058-91caba00-c42f-11e9-8842-29d659c35fcb.png)


******************** **Active Member Locator - Website** ******************** 
I have looked into this issue and notice issue with unexpected check to stop expoting don't published and unsubscribed member. I just remove that additional check and now it's exporting with proper count. Please see exported file.
 
[ActiveMemberReport-Website-8802 (3).xlsx](https://github.com/stellaballa/AERA/files/3525014/ActiveMemberReport-Website-8802.3.xlsx)

**Comment by kbt1** [comment]
good to go
