### ISSUE TITLE
Online Training Reports + Updates

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#132]
@kbt1  and @stevefox3781  We went over the request and we have some questions:

1) Make the report I am asking for with student names and grades like the dashboard and export into Excel Spreadsheet for Group Leader Login Screen 

I attached an Excel, please let us know if this is the report you need. 
[group-leader-report.xlsx](https://github.com/stellaballa/AERA/files/4221990/group-leader-report.xlsx)

Make a button on the screen to alpha the names by last name for Group Leader Login Screen
Do you mean a filter? Or the search box? 

Program so that no matter the order I enter the names, they are automatically alphabetized by last name when listed for Group Leader
So the ordering will be alphabetical by last name, correct?

**Comment by kbt1** [comment]
1- The sample report is exactly what we are looking for. This is for any group leader for the Certification course and Sam Tech.

2- Button on screen to alpha last names:
Yes, be able to filter the names and make them alpha by last name for Group Leader.

3- Automatically alpha last names no matter the order they are entered for Groups: 
It seems the order I enter Groups are the way they are listed on the dashboard.
It would be nice if they are automatically alpha after I enter them in the system.

In speaking with a couple instructors (Group Leaders) having the students listed alpha by last name instead of the order I enter them in the system would make things easier. It would probably make things easier if they are automatically alpha so we dont have to explain the filter part but whatever we can do would work. 

let us know if you have any other questions.

thank you!

**Comment by stellaballa** [comment]
Thanks @kbt1  I would recommend implementing the following features:
1) Ability to download the dashboard report
2) Sort the name by alpha the last name. 

As for the filter, we should hold off and see if the group leader need to filter the name in other ways.

**Comment by kbt1** [comment]
sounds good.
Let us know the quote.
