### ISSUE TITLE
Monthly Report - Quick Membership Count

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/AERA#153]
When we add a date, it seems to be pulling from the actual date and not the date entered if that makes sense. We need to be able to pull information on the first day of every month to get accurate counts even if we were to pull it today. I also need this information for our audit next week. Can you please look into this right away and see what the issue is? Karen said on 8/1/2020 we were in the 1980's for membership counts and when we pull the report today, it is showing 1994, which is all our membership. Any questions let me know. 

![image](https://user-images.githubusercontent.com/26387391/89538484-3d475880-d7c0-11ea-9983-eac624a3533a.png)
[MembershipQuickMembershipCountReport-5900 .xlsx](https://github.com/stellaballa/AERA/files/5035110/MembershipQuickMembershipCountReport-5900.xlsx)

**Comment by stellaballa** [comment]
@SagarPC  please take a look

**Comment by SagarPC** [comment]
@stevefox3781 We checked this report logic and it's implemented to get the current status of the system. I think your request is like the history result, like if you add 8/1/2020 by today then the result should active member on that day even those inactive member is active today.

_Example: 
8/1/2020 active member is 1980, till today 15 members paid for new/renew the subscription. so total 1995 member is active till today. 

but when we add 8/1/2020 is should not consider renewed newly added 15 members, because those members were not active on  8/1/2020 date._

Is that correct? If this is the case then we need to change existing logic and lookup for the dues database to check that specific date status.

**Comment by stevefox3781** [comment]
Yes that is correct the way you explained it.

**Comment by SagarPC** [comment]
@stevefox3781  I added dues transaction lookup for the Quick count report and now it's showing 1981 count for the date "08/01/2020". Please see attached file for the reference.

[MembershipQuickMembershipCountReport-8802 (1).xlsx](https://github.com/stellaballa/AERA/files/5050455/MembershipQuickMembershipCountReport-8802.1.xlsx)

**Comment by stevefox3781** [comment]
Seems to be working correctly. Thank you for looking into this and getting it fixed, greatly appreciate it.
