### ISSUE TITLE
Monthly Report - Quick Membership Count

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#154]
Hi Stella:

A week ago Steve had Sagar fix this and now it seems off.

The Quick Membership Report is inaccurate .
If I enter 8/1/2020, the count is 1981 which is accurate
Now If I change it to get a current count as of today 8/11/2020, the count is 1988 which is wrong
If I go to the export tab, pull a list of all current membership:
Member Type-All, Status-Active, Country-All, click export
the spreadsheet comes up with 2003 active members.
This is leading me to believe the quick membership count of 1988 with date of 8/11/2020 is wrong.  (See samples)

We need to be able to pull the Quick Membership AND Prosis counts for any day of the month.

please let me know if you have any questions. 

[Export Tab Current Members-Sample.xlsx](https://github.com/stellaballa/AERA/files/5058024/Export.Tab.Current.Members-Sample.xlsx)
[MembershipQuickMembershipCountReport as of 8-11-2020.xlsx](https://github.com/stellaballa/AERA/files/5058025/MembershipQuickMembershipCountReport.as.of.8-11-2020.xlsx)
[MembershipQuickMembershipCountReport as of 8-1-2020.xlsx](https://github.com/stellaballa/AERA/files/5058027/MembershipQuickMembershipCountReport.as.of.8-1-2020.xlsx)

**Comment by stellaballa** [comment]
@SagarPC  can you please take a look?

**Comment by SagarPC** [comment]
@kbt1 We updated logic for the history search and now we are looking into Dues Transaction to check the user was active on the requested date or not.  We found total of 14 members updated directly without making any entry in Dues Transaction. Please see the below image.

As per the Dues Transaction, this user expired on 08/01/2020, and after that no updated record in Dues Transaction.
![image](https://user-images.githubusercontent.com/31076567/89978060-489bf780-dc8a-11ea-8234-6fca267acc0e.png)

If we check the Membership then it's shown active because these members subscriptions updated directly from Members screen. 
![image](https://user-images.githubusercontent.com/31076567/89978085-56517d00-dc8a-11ea-8808-f83da7681bca.png)

**14 Member List not added in Dues but update subscription directly.**
17024
43341
1033
3423
3142
3063
12658
37612
979
44413
44471
44660
44679
44683

Please let us know how you would like to manage this case!

**Comment by kbt1** [comment]
17024 - monthly checking extended date until payment is processed 8-15
43341 - monthly payment processed 8/10
1033 - comp membership
3423 - 1 yr comp membership
3142 - comp membership
3063 - comp membership
12658 - comp membership
37612 - comp membership
979 - payment deposited under wrong member number, manually adjusted membership
44413 -comp membership
44471 - 1 yr comp membership
44660 - monthly payment processed 8/10
44679 - comp membership
44683 - comp membership

i understand you pull according to when paid in dues but we need the number pulled according to expiration date in MMS.
can this be done? this may fix the issue.

**Comment by SagarPC** [comment]
@kbt1  We can provide one additional option like export data based on dues history if it's selected we check for the dues transaction else we will export report based on the current situation of the Members. 

Please let us know if this solution will work. Also, suggest if any other

**Comment by kbt1** [comment]
that should be good.
i believe if you check for expiration date, it should bring up current numbers no matter what day of the month it is, which is what i need. Since we have situations where payments don't show up in Dues.

**Comment by SagarPC** [comment]
@kbt1 We added checkbox before the export button if it's selected we go fo the Dues Transaction and check for the history. If it's unchecked then we will search based on members current status only.  Please check our update and let us know if any change in this.

![image](https://user-images.githubusercontent.com/31076567/90255081-653e5800-de61-11ea-8553-abbf67b9edd0.png)

**Comment by kbt1** [comment]
works good.
