### ISSUE TITLE
Prosis Pro - Member in UK getting error "This Site Cant Be Reached"

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#165]
I have a member in the United Kingdom that has rebooted and cleared cookies. (not same as last week)
He keeps getting This Site Cant be Reached when he tries to login.
I was able to login under his credentials.
He is logging in on a computer with Chrome.

user name: kingcomponents
password: 23319797!

Any ideas?

**Comment by SagarPC** [comment]
@kbt1 : Yes, I think there is some change done in server acess by someone and it's now allowing only US IP to access website.

Please contact Server guy to allow webite access to all users instead of only US.

We are also not able to acess Wesbiste and Server both. I sent email to you about the same issue.

**Comment by kbt1** [comment]
looks like there was an issue on the server.
it is fixed and the member that couldnt get access is able to get back in today.
all is good.
