### ISSUE TITLE
AERA Certification Course - BROKEN

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#177]
Sagar
I have tried adding a new student in the online certification course and none of the check mark boxes are working to check what course they want to take so I cant save the student. 
Can you look into this please.

![image](https://user-images.githubusercontent.com/26387044/103821803-90a22900-5034-11eb-89b5-2d3fed0f7d33.png)

If you look at these logins, looks like none of them are working.

ifox | allindeng
srauseo | 02347
mijes | big.cress
jdkelley | mwmachine

looks like something broke.

let me know when fixed.

Thank you!

**Comment by kbt1** [comment]
Both Cylinder Head Machinist and Engine Machinist should be checked

**Comment by SagarPC** [comment]
@kbt1 I checked all users provided by you and all are working. I also check the selection and found "Cylinder Head Machinist" and "Engine Machinist" already selected.

It may temporarily issue because yesterday VCS working on aeraedu SSL issue.

Please check and let me know if you are still facing an issue with aeraedu

**Comment by kbt1** [comment]
Seems things are working good again.
