### ISSUE TITLE
Windows 11 formatting issues

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERA#248]
Sagar, 
We have a member that just upgraded to Windows 11 and when they go to print information out of PROSIS the margin for everything under their company over is shifted to the right and more compact. Do you have a way to test if this is an issue with Windows 11 and if there's something we need to reformat? I'm also looking into getting someone on Windows 11 on my end to see if we can duplicate the issue. 
Thanks,
Amanda

**Comment by SagarPC** [comment]
@amandagoyette can yo please provide below detail?

1) screenshots or PDF which they exported from the system?
2) Which PDF they print,I means Engine Spec or Bulletin or any other?
3) Prosis Pro user details.

It will help us to look into this issue.

**Comment by amandagoyette** [comment]
Sorry Sagar, my week got away from me.  I can get screen shots but it's been Engine Specs from what he told me.  
Username: BMMachining
Password: 33537*

**Comment by SagarPC** [comment]
@amandagoyette  I downloaded PDF from the Windows 11, please see attached file.

[DETROIT-DIESEL-60-SERIES-221005153520.pdf](https://github.com/stellaballa/AERA/files/9714756/DETROIT-DIESEL-60-SERIES-221005153520.pdf)

**Comment by amandagoyette** [comment]
I left him a voicemail this morning letting him know we cannot duplicate it and asked him to send me a screenshot or print and scan me a page to look at. I will let you know when I hear.

**Comment by amandagoyette** [comment]
![Preview Print Screen](https://user-images.githubusercontent.com/26386841/194080794-79e6707a-3009-4cc6-b44b-33949eece9cd.jpg)
![Printed Document](https://user-images.githubusercontent.com/26386841/194080802-b1367d25-4496-4d26-846e-05fcff4a82fa.jpg)

**Comment by amandagoyette** [comment]
@SagarPC The images I shared are what he's getting.

**Comment by amandagoyette** [comment]
@SagarPC His PROSIS Screen is also showing a lot of gray on the sides when it's full screen if that helps you deduce what's going on: 
![PROSIS View 2](https://user-images.githubusercontent.com/26386841/194081344-31ba4538-59d1-4a80-a681-f93905495b0a.jpg)
![PROSIS View](https://user-images.githubusercontent.com/26386841/194081348-5e9546ce-fb69-409c-a8d4-6deb240ff2aa.jpg)

**Comment by SagarPC** [comment]
@amandagoyette Please see our comments below.

**Print:** For the Print User need to download PDF and after that they can print. Please see below image.
1. Please don't use direct print option, we will update this function with next release and provide direct export PDF function instead of view in windows. 
2. Please see attached image#2, user can download PDF and print from that downloaded PDF. 

![image](https://user-images.githubusercontent.com/31076567/194222943-b2ec1112-ffcf-495c-ab2b-9c71b4c54b29.png)

**Side Space:**  We have fixed width for the desktop version and based on resolution, content area load in center position and leave gray color in rest of the position.

**Comment by kbt1** [comment]
to be corrected in new Desktop update.

**Comment by amandagoyette** [comment]
Thank you Sagar everything is looking like it's on his end I'll call him this morning and see what we can get solved.

Amanda Goyette
Administrative Assistant
AERA Engine Builders Association
________________________________
