### ISSUE TITLE
MMS-Can not email 6 month renewal invoice

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#276]
Hi Sagar,

Not sure why this is not working.
I cant email a 6 month renewal invoice to member #44442. See image below.
![image](https://github.com/stellaballa/AERA/assets/26387044/e94a7d51-a2ea-4749-be57-bcc68e2ad736)

thank you!

**Comment by SagarPC** [comment]
@kbt1 

We checked and found that user having Monthly Prosis Pro plan and because it's not allowing email or print invoice from the listing screen. We have check in system to exclude monthly user from the email/print invoice from the listing screen.

![image](https://github.com/stellaballa/AERA/assets/31076567/d68677eb-de1c-4a0e-8d19-44ff57f9a718)

Please let me know if there is any logic adjustment is required.

Regards,

**Comment by kbt1** [comment]
Thank you, i didnt notice Prosis was set to Monthly. I changed it and the 6 month membership renewal emailed.
