### ISSUE TITLE
AERA Certification

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#28]
i have a person that took the Mid-Term and then the system times out. He says he passed at 82%.
i dont see a score but i was wondering if you do on your end?  i told him he will have to retake it which he wasnt very happy about.
Can you look at his account and see if he did complete the Mid Term or when it timed out, it wiped his score.

![image](https://user-images.githubusercontent.com/26387044/31083599-b4e0eef2-a757-11e7-944d-ade16f088209.png)
i would like to let him know ASAP before he starts getting aggravated and retakes the course again. i guess it took a few tries for him to pass.

**Comment by SagarPC** [comment]
I have looked into database and not found any information related to Mid Term exam for "kylejo" user. 

There is no single tries recorded in database for Mid Term may be because of time out.  User need to click on "Submit Answer" button to record exam in database.

![image](https://user-images.githubusercontent.com/31076567/31121921-a69c6bea-a857-11e7-88b2-72f3d09f6c51.png)

**Comment by kbt1** [comment]
thank you for checking
