### ISSUE TITLE
Error when Running Report in MMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#280]
When I run this report, I get the following error:
![image](https://github.com/stellaballa/AERA/assets/26387044/68c694c8-2e8f-444b-afd9-7183e4f9fef2)

![image](https://github.com/stellaballa/AERA/assets/26387044/d8fdffa1-e091-4d25-a343-2b3c1a7a908f)

I click yes, and report seems to come up.

Also, can you make the dollar amounts columns like this $460.00 and not 460.0000
![image](https://github.com/stellaballa/AERA/assets/26387044/03472833-aa59-4af6-9bfe-2f3ef23c1c63)

thank you!

**Comment by SagarPC** [comment]
@kbt1 We are done with the changes in report. Please see attached doc for the reference.

Also, about the warning message on the Excel open you just have to click on "Yes" and open it. It's showing this message because we used .NET Class library to create Excel file and did some formatting inside. You can ignore it.

Please let us know if you have any questions. 

[aeramms_upload_changes_2024_06_20.docx](https://github.com/user-attachments/files/15913715/aeramms_upload_changes_2024_06_20.docx)

**Comment by kbt1** [comment]
thank you!
