### ISSUE TITLE
AERA Summary Report Corrections for 2024 Online Training

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#281]
Hi Sagar,

I have found a couple things that need to be corrected.
I have highlighted in Orange (7), ones that should not go towards count.
Can you create 2 new types? ADMIN and Instructor and allow NO Status.
Both of these should **not** be included in the count of logins/users.

there is 1 highlighted in yellow, Aaron Burnett, comes up Passed, however, he has not completed the final exam so he should be in process.
[AERA_SummaryReport_2024_Corrections.xlsx](https://github.com/user-attachments/files/16236380/AERA_SummaryReport_2024_Corrections.xlsx)

there should only be 1 passed and the rest should all be In Process.

Teacher Dashboard Corrections:
![image](https://github.com/user-attachments/assets/02ed3327-38ed-45e4-bb4a-38a62284677b)

In the Mid Pass and Final Pass, the circles show progress however, there is none.
Also, it should read In Process not in progress. Can you also change so it reads Mid Term Pass. (See attached)

let me know if you have any questions.
Thank you!
Karen

**Comment by SagarPC** [comment]
@kbt1 We are working on this request. We will send you update on this very soon.

Regards,

**Comment by SagarPC** [comment]
@kbt1  We uploaded requested changes on old and new both version. Please see attached document for your reference.

https://www.aeraedu.com/2024
https://www.aeraedu.com/

[AERA EDU Doc.docx](https://github.com/user-attachments/files/16284485/AERA.EDU.Doc.docx)

**Comment by kbt1** [comment]
Hi Sagar,
Nothing seems changed on my end. 

Karen

**Comment by kbt1** [comment]
Also, can you change just the Final Pass to Final Exam Pass?

**Comment by SagarPC** [comment]
@kbt1  We did not added 2 new selection, because Admin and Instructor (Group Leader) we identify automatically. 

Admin - Only we can create new admin account.
Instructor - We considered "Group Leader" as "Instructor"  

We identify both and showing from our end and show blank Status in report. Please let me know if any change required in this logic.
![image](https://github.com/user-attachments/assets/42de384b-6823-4a1b-b700-d06d3136f1cd)

Also, for the teacher dashboard, please let us know which login detail you are using. We will check for that user specific and update you.

Regards,

**Comment by kbt1** [comment]
ok, yes, that will work.
this is the instructor login: 
![image](https://github.com/user-attachments/assets/b745aa29-3b40-47e4-a5df-24b8a8ee3e62)

**Comment by SagarPC** [comment]
@kbt1  

We checked for this leader and it's showing yellow circle. Please let me know if any changes required.

![image](https://github.com/user-attachments/assets/3ef8766c-6a65-4394-a7fd-983bd04fc66c)
