### ISSUE TITLE
MMS- printing dues and prosis invoices

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#32]
I went to print invoices due in 45 days
this is what i selected on the main page
![image](https://user-images.githubusercontent.com/26387044/31280851-5e807ab8-aa73-11e7-8f56-ce386ad9b40a.png)

This is the list of invoices i got
[Expire in 45 days invoices.pdf](https://github.com/stellaballa/AERA/files/1362883/Expire.in.45.days.invoices.pdf)

There are invoices that are printing with expiration dates of 1/1/2018, 12/1/16, 11/1/16.
See attached listing of invoices.  ID#990, 1685, 9635, 10102, 27458 are examples of wrong info being pulled. This needs to be fixed ASAP so I can print these and get them mailed. I didnt notice this last month but maybe i missed it.  
The only reason both Membership and Prosis Pro fee's should be on the invoice is if they both expire together or they are 3 months apart from each other. 
the invoices i pull should all expire 11/1/2017 + or - 3 months. so if membership expired 9/1/17 and Prosis expires 11/1/17, both will be on invoice or vice versa.

let me know if you have any questions.

**Comment by stellaballa** [comment]
@SagarPC We should have implemented this feature, and I remember testing it and it was working properly. Can you please look into it?

**Comment by SagarPC** [comment]
@stellaballa : Please see below for my comment with requirement. All function working as per requirement.

https://github.com/omnitekinc/AERA_MSS_Clients/issues/186#issuecomment-306820485
Member# 990 : Expiration less than 90 days and that's why it's exporting in invoice.
Member# 9635, 27458: Membership and Prosis Pro both having less than 90 days gap so both printed togather.

https://github.com/omnitekinc/AERA_MSS_Clients/issues/86#issuecomment-298397673
- If Membership and Prosis Pro expired within 90 days then generate an invoice with both items

https://github.com/omnitekinc/AERA_MSS_Clients/issues/197
- Exclude only those member who having expiry older than 1.5 year.
- Member# 1685, 10102 not expired within 1.5 year.

**Comment by kbt1** [comment]
ID#1685 expired 12/1/16 - invoice pulled
ID#10102 expired 11/1/16 - invoice pulled
ID#32809 expired 6/1/16 - invoice pulled.

Can we make a change and Exclude only those member who having expiry older than 6 months.
so we can avoid printing these invoices above.

**Comment by SagarPC** [comment]
@kbt1 :

+++++++++++++++
ID#1685 expired 12/1/16 - invoice pulled
ID#10102 expired 11/1/16 - invoice pulled
ID#32809 expired 6/1/16 - invoice pulled.
Can we make a change and Exclude only those member who having expiry older than 6 months.
so we can avoid printing these invoices above.
+++++++++++++++
We have taken action and changes logic to 6 month instead of 1.5 year for above case.

**Comment by kbt1** [comment]
i will be printing invoices and double check and close when done.
thank you!
