### ISSUE TITLE
MMS - Dues Bulk Batch    HELP NEEDED ASAP!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#33]
Hi Stella
I did this original bulk batch and posted it.
then I went to do a 2nd batch, renamed the spreadsheet to pull it in and noticed it was wrong, so i deleted it. 
Looks like it deleted the Bulk Batch I posted and now everything is messed up..........Please call me with any questions. I need this fixed ASAP if possible.

![image](https://user-images.githubusercontent.com/26387044/31458649-519edbca-ae86-11e7-8f41-42005b2bc5f0.png)
![image](https://user-images.githubusercontent.com/26387044/31458657-5b449278-ae86-11e7-991b-1cb8a4dcf37d.png)

Any way this can be put back in? All the records have been posted and expiration dates updated.
Here is the Bulk Batch.

[Monthly Credit Cards 10-11-17.xlsx](https://github.com/stellaballa/AERA/files/1376732/Monthly.Credit.Cards.10-11-17.xlsx)

**Comment by stellaballa** [comment]
Hi Karen,
I will give you a call in 30min.
Stella

Stella Lai, CEO
Parts Connect, Inc.
www.partsconnect.io


On October 11, 2017 at 11:19:05 AM, kbt1 (notifications@github.com) wrote:

Hi Stella
I did this original bulk batch and posted it.
then I went to do a 2nd batch, renamed the spreadsheet to pull it in and
noticed it was wrong, so i deleted it.
Looks like it deleted the Bulk Batch I posted and now everything is messed
up..........Please call me with any questions. I need this fixed ASAP if
possible.

[image: image]
<https://user-images.githubusercontent.com/26387044/31458649-519edbca-ae86-11e7-8f41-42005b2bc5f0.png>
[image: image]
<https://user-images.githubusercontent.com/26387044/31458657-5b449278-ae86-11e7-991b-1cb8a4dcf37d.png>

Any way this can be put back in? All the records have been posted and
expiration dates updated.
Here is the Bulk Batch.

Monthly Credit Cards 10-11-17.xlsx
<https://github.com/stellaballa/AERA/files/1376732/Monthly.Credit.Cards.10-11-17.xlsx>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/stellaballa/AERA/issues/33>, or mute the thread

**Comment by kbt1** [comment]
thank you

**Comment by kbt1** [comment]
Stella, these are the **2 spreadsheets that need to be reloaded into the 11-01-17 Bulk Entry by KT**
ALL records exp dates have been updated [Monthly Credit Cards 10-11-17.xlsx](https://github.com/stellaballa/AERA/files/1376870/Monthly.Credit.Cards.10-11-17.xlsx)
NO expiration dates have been updated for this set [Monthly Credit Cards 10-11-17 - batch2.xlsx](https://github.com/stellaballa/AERA/files/1376871/Monthly.Credit.Cards.10-11-17.-.batch2.xlsx)
**The bulk batch should total $12145.65 once all updated.**
will you be able to update the batch 2 expiration dates? all of batch 1 i created and posted so all records have been updated.
once your done, let me know so I can reprint the report.

**Comment by stellaballa** [comment]
Hi @kbt1 discussed this with @SagarPC he said he needs some time to look into the database to make sure there's no potential issue if we load the data back in. 
@SagarPC  Once you checked, please load both Excel for @kbt1 as 1 batch.

System issue: Looks like current system can't handle multiple batches on the same day, when Karen created batch 1 today and posted it, she was able to create batch 2. However, the system doesn't seem to know that those are 2 separate batches, even though the first batch has been posted. We need to look into the system to match sure it can handle bulk batches the same way as regular batches. Ability to create multiple batches on the same day, and the batches are independents of each other.

**Comment by kbt1** [comment]
let me know what you figure out. 

Data for the bulk batch in the system needs to entered back in cause all the expiration dates have been updated once i posted it.

I can always create a regular batch for the 2nd spreadsheet.

**Comment by SagarPC** [comment]
@kbt1 : We have found cause and resolved this issue. We have get back closed batch and now it's showing proper result and also loaded 2nd file under open batch. Please review Open batch and if you found all okay then post that 2nd batch.

**Comment by kbt1** [comment]
Looks GREAT!  Thank you!!!!!
