### ISSUE TITLE
Prosis Pro - printing issue

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#46]
Hi Stella
I spoke to a member who is having printing issues:

Rick
Precision Machine ID#1573
573-635-7214
**Win10 using the Edge Browser**
Under settings, he is allowing pop ups from prosispro.com
I suggested he try google chrome
**The printing issue just came about after some win10 update so it might be something related to the Edge Browser or Win10.**
**When he prints, he gets all the menus to come up but when the page he wants to print comes up on the screen, it’s a blank sheet.**
I thought I heard of this but I don’t recall the issue. 
 
Any suggestions. I told him we would probably get back with him next week.
He can print by right clicking on the page but it doesn’t print as nice as using the print function in the program.

Thanks. Karen

**Comment by stellaballa** [comment]
Thanks Karen @kbt1 We will look into this

**Comment by SagarPC** [comment]
@kbt1 : We have resolved this issue on live. Please inform that client to check again.

www.prosispro.com

FYI:
This issue because of windows update and Microsoft have no solution on that. We taken alternate way to generate pdf file for client to make this issue resolved.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7045462/

**Comment by kbt1** [comment]
Thank you. I will call the member and have him check if he can print.
Member is VERY HAPPY this is fixed!!!  Thank you very much!!!!!!!
