### ISSUE TITLE
Prosis Pro

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#49]
Stella
I have a member in Kuwait that uses Prosis Pro Desktop. Their license key keeps coming up invalid.
I had him make sure his date was mm/dd/yyyy. I recall this being an issue. he changed it and it works.
His reply was:
I tried out your suggestion and it worked fine. It looks like a date format problem. However, here in Kuwait (as well as Asia, Europe) we are using the date/month/year format. So, changing this format will cause problems with all our other applications and document work.
I’m wondering if there is a way for the PROSIS PRO software to accept other date-time formats?

is there anything that can be done to fix this? 
Thanks
Karen

**Comment by stellaballa** [comment]
@kbt1 I remember discussed this when we started the ProsisPro project, and the easiest work around is to ask the oversea members to change the format of their date formate. Otherwise we will have to build in a function that will check the computer date format, which could become complicated. If this is a function AERA would like to add to the software, we can discuss further.

**Comment by kbt1** [comment]
If this member changes his date format then other programs he uses doesnt work.
I guess this is something Steve can decide. I will let the member know the date format needs to be set as we request at this time.
