### ISSUE TITLE
Order Form not working

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#64]
Karen reached out to me this morning because she isn’t receiving any orders that she sends via the Product Order Form in the Member Management System.  After testing different sites and emails we’ve narrowed it down to being specific to MMS.  Can you see if you all can deduce what’s going on?  I’m more than happy to pull VCS into the loop if needed, but everything is pointing to an issue with MMS vs. email.

**Comment by SagarPC** [comment]
I tried same and received email. Please see below reference image. 

can you please try again and provide me step which you are following? 

![image](https://user-images.githubusercontent.com/31076567/39616663-33410878-4f9a-11e8-8e41-7539639662bf.png)
![image](https://user-images.githubusercontent.com/31076567/39616729-8498b374-4f9a-11e8-88a6-b2076048cbd9.png)
![image](https://user-images.githubusercontent.com/31076567/39616637-16f04e5e-4f9a-11e8-83de-d4d717714e58.png)

**Comment by kbt1** [comment]
This is what i have tried 3 times on Thursday and didnt work. I was out on Friday and Amanda sent me 2 renewals and I never got them. 
![image](https://user-images.githubusercontent.com/26387044/39711160-832387c0-51e4-11e8-8357-7a558119717a.png)
1. Create the order
2. click on send email
3. Email successfully sent
![image](https://user-images.githubusercontent.com/26387044/39711204-aac9a336-51e4-11e8-9972-5e7594723146.png)
4. No email received to Karen@aera.org   - waited 5-10 minutes. nothing.

Sagar or Stella, can you send a test to me today since I am in the office.

**Comment by SagarPC** [comment]
Please check spam folder. I think email should be in spam folder.

**Comment by kbt1** [comment]
Nothing in my junk folder

**Comment by kbt1** [comment]
I just created an order and had it sent to Amanda and she never got it.

**Comment by kbt1** [comment]
emailed forms seem to be coming through.
if there are more issues, i will let you know.
