### ISSUE TITLE
info@aera.org for 30 days non member demo

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERA#74]
@SagarPC Can you check to see if info@aera.org email has been updated on the 30 days non member demo? Karen is still getting email on the webmail.

Karen can tell you what email address it goes to currently. That should stay the same. The problem is it’s going to the old VCS network instead of the new Office 365. I know Sagar & VCS fixed the orders, tech emails, and some others. This one was missed it seems. If we need VCS to do something I can definitely involve them I just wasn’t sure where to start.

**Comment by SagarPC** [comment]
@stellaballa : I already sent below email to Mark on Sep 6, 2018 and after that, there is no confirmation from the Mark.

Email Subject: follow up for Stella
++++++++++++++++++++++
Hi Mark,

We are using "tech@aera.org" email as from email for the Tech Call, "liveerror@aera.org" & "demoerror@aera.org" for error tracking.

so we need "info@aera.org", "tech@aera.org", "liveerror@aera.org" & "demoerror@aera.org" to be available as from email address with new setup "aera-org.mail.protection.outlook.com".

Regards,
++++++++++++++++++++++

**Comment by anthonypartsconnect** [comment]
We received this message today in an email.  Stella shared with us Sagar. I believe we need them to update the action on Demo program.  Do you see this reply as any action needed on our end? 
Thanks. 

"Good afternoon, Stella!

A couple of weeks back our team worked with Sagar to update the SMTP information for the ProsisPro program since AERA was switching to a different email server. That same information will need to be punched into the Demo program since it is still using the old email server information and is relaying to the wrong device. For reference, here is the information needed to update and correct the issue for the Demo program:

SMTP Relay Information:
SMTP server: aera-org.mail.protection.outlook.com
Port: 25


note: email address should not matter so long as it is from one of the following that have been setup:
prosispro@aera.org

info@aera.org
tech@aera.org
liveerror@aera.org
OR
demoerror@aera.org

Please let us know if there is anything else we can further assist with.

Kind regards,

-Cody"

**Comment by SagarPC** [comment]
Update Demo program with new SMTP setting.

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Did you do this on our end?  You "updated Demo program with new SMTP setting?"  
Or this is action they (VCS) needed to take.

I just need to go back to AERA and VCS and confirm if you did do this on our end.  

Thanks for clarifying.

**Comment by SagarPC** [comment]
@anthonypartsconnect : I already replied like I updated Demo program with new SMTP setting.

Please let me know if any other action they suggested to do.

**Comment by anthonypartsconnect** [comment]
Thanks.  I will follow up with AERA and VCS if needed.

**Comment by anthonypartsconnect** [comment]
The issue should be resolved now. Thank you Sagar.
